import { User, Mission, PointTransaction, Badge } from './types';

const BADGES: Badge[] = [
  { id: 'first-mission', name: 'First Mission', description: 'Completed your first mission', icon: '🎯', earnedAt: '2026-01-15' },
  { id: 'rapid-delivery', name: 'Rapid Delivery', description: 'Completed a mission 30+ days early', icon: '⚡', earnedAt: '2026-02-01' },
  { id: 'bridge-builder', name: 'Bridge Builder', description: 'Led a cross-departmental mission', icon: '🌉', earnedAt: '2026-02-20' },
  { id: 'quality-star', name: 'Quality Star', description: 'Received 5/5 on validation review', icon: '⭐', earnedAt: '2026-03-01' },
  { id: 'mentor', name: 'Mentor', description: 'Helped develop another contributor', icon: '🧑‍🏫', earnedAt: '2026-03-10' },
  { id: 'high-stakes', name: 'High Stakes', description: 'Completed a mission worth 2000+ points', icon: '💎', earnedAt: '2026-03-15' },
];

export const SEED_USERS: User[] = [
  {
    id: 'u1',
    name: 'Ana Torres',
    avatar: '/avatars/ana.svg',
    title: 'Product Strategy Lead',
    department: 'Product',
    roles: ['creator', 'curator'],
    skills: ['Product Strategy', 'OKR Design', 'Data Analysis', 'User Research'],
    reputation: { total: 6200, impact: 2600, execution: 1800, collaboration: 1200, growth: 600 },
    level: 4,
    levelName: 'Master',
    pointsBalance: 3450,
    badges: [BADGES[0], BADGES[2], BADGES[5]],
    joinedAt: '2025-09-01',
    completionRate: 0.94,
    missionsCompleted: 3,
    missionsCreated: 12,
    missionsValidated: 5,
  },
  {
    id: 'u2',
    name: 'Marcus Chen',
    avatar: '/avatars/marcus.svg',
    title: 'Senior Software Engineer',
    department: 'Engineering',
    roles: ['solver'],
    skills: ['TypeScript', 'React', 'Python', 'SQL', 'Cloud Architecture', 'Machine Learning'],
    reputation: { total: 4800, impact: 1900, execution: 1500, collaboration: 900, growth: 500 },
    level: 3,
    levelName: 'Expert',
    pointsBalance: 5200,
    badges: [BADGES[0], BADGES[1], BADGES[3]],
    joinedAt: '2025-10-15',
    completionRate: 0.92,
    missionsCompleted: 18,
    missionsCreated: 2,
    missionsValidated: 0,
  },
  {
    id: 'u3',
    name: 'Priya Sharma',
    avatar: '/avatars/priya.svg',
    title: 'Technical Lead',
    department: 'Engineering',
    roles: ['validator', 'solver'],
    skills: ['System Design', 'Code Review', 'DevOps', 'TypeScript', 'Go', 'Security'],
    reputation: { total: 7500, impact: 3000, execution: 2300, collaboration: 1500, growth: 700 },
    level: 4,
    levelName: 'Master',
    pointsBalance: 4100,
    badges: [BADGES[0], BADGES[3], BADGES[4], BADGES[5]],
    joinedAt: '2025-08-20',
    completionRate: 0.97,
    missionsCompleted: 10,
    missionsCreated: 4,
    missionsValidated: 22,
  },
  {
    id: 'u4',
    name: 'Jordan Blake',
    avatar: '/avatars/jordan.svg',
    title: 'Innovation Program Manager',
    department: 'Strategy',
    roles: ['curator', 'creator'],
    skills: ['Program Management', 'Innovation Frameworks', 'Stakeholder Management', 'Data Visualization'],
    reputation: { total: 3100, impact: 1300, execution: 900, collaboration: 600, growth: 300 },
    level: 3,
    levelName: 'Expert',
    pointsBalance: 2800,
    badges: [BADGES[0], BADGES[2]],
    joinedAt: '2025-11-01',
    completionRate: 0.88,
    missionsCompleted: 6,
    missionsCreated: 15,
    missionsValidated: 8,
  },
  {
    id: 'u5',
    name: 'Leila Okonkwo',
    avatar: '/avatars/leila.svg',
    title: 'Junior Data Analyst',
    department: 'Analytics',
    roles: ['solver'],
    skills: ['SQL', 'Python', 'Data Visualization', 'Statistics'],
    reputation: { total: 820, impact: 340, execution: 250, collaboration: 150, growth: 80 },
    level: 2,
    levelName: 'Contributor',
    pointsBalance: 680,
    badges: [BADGES[0]],
    joinedAt: '2026-01-10',
    completionRate: 0.80,
    missionsCompleted: 4,
    missionsCreated: 0,
    missionsValidated: 0,
  },
];

export const SEED_MISSIONS: Mission[] = [
  {
    id: 'm1',
    title: 'Build Real-Time Product Metrics Dashboard',
    description: 'Create a real-time dashboard that pulls data from 3 internal data sources (Salesforce, Mixpanel, internal PostgreSQL) and displays key product OKRs with drill-down capability. Must support responsive design and auto-refresh every 5 minutes.',
    successCriteria: [
      'Real-time data pull from 3 data sources',
      'Responsive design works on desktop and tablet',
      '95% uptime over 30-day monitoring period',
      'Sub-3-second load time for dashboard views',
    ],
    category: 'strategic',
    rewardModel: 'fixed',
    estimatedHours: 120,
    deadline: '2026-05-15',
    requiredSkills: ['React', 'SQL', 'Data Visualization'],
    complexity: 2.5,
    urgency: 1.4,
    strategicImportance: 1.3,
    baseReward: 4200,
    dynamicReward: 4330,
    status: 'in_progress',
    creatorId: 'u1',
    solverId: 'u2',
    validatorId: 'u3',
    applicants: [
      { userId: 'u2', proposal: 'I can build this using Next.js + D3.js with a real-time WebSocket layer. Estimated 3 weeks.', appliedAt: '2026-03-05' },
      { userId: 'u5', proposal: 'I would use Python/Streamlit for rapid prototyping with SQL connectors.', appliedAt: '2026-03-06' },
    ],
    activityLog: [
      { id: 'a1', type: 'created', userId: 'u1', message: 'Mission posted to marketplace', timestamp: '2026-03-01T09:00:00Z' },
      { id: 'a2', type: 'applied', userId: 'u2', message: 'Marcus Chen submitted application', timestamp: '2026-03-05T14:30:00Z' },
      { id: 'a3', type: 'applied', userId: 'u5', message: 'Leila Okonkwo submitted application', timestamp: '2026-03-06T10:15:00Z' },
      { id: 'a4', type: 'assigned', userId: 'u1', message: 'Marcus Chen selected as solver', timestamp: '2026-03-07T11:00:00Z' },
    ],
    createdAt: '2026-03-01',
    submittedAt: null,
    completedAt: null,
  },
  {
    id: 'm2',
    title: 'Automate Monthly Regulatory Compliance Reports',
    description: 'Build an automated pipeline that generates monthly regulatory compliance reports from our data warehouse. Currently this process takes 3 analyst-days per month. Target: fully automated with human-in-the-loop review step.',
    successCriteria: [
      'Reports generated automatically by 5th business day of each month',
      'Human review step integrated with approval workflow',
      'Error rate below 0.1% compared to manual reports',
      'Documentation for compliance team to manage the pipeline',
    ],
    category: 'operational',
    rewardModel: 'fixed',
    estimatedHours: 80,
    deadline: '2026-04-30',
    requiredSkills: ['Python', 'SQL', 'Data Visualization'],
    complexity: 2.0,
    urgency: 1.6,
    strategicImportance: 1.1,
    baseReward: 2816,
    dynamicReward: 2900,
    status: 'open',
    creatorId: 'u4',
    solverId: null,
    validatorId: null,
    applicants: [],
    activityLog: [
      { id: 'a5', type: 'created', userId: 'u4', message: 'Mission posted to marketplace', timestamp: '2026-03-20T08:00:00Z' },
    ],
    createdAt: '2026-03-20',
    submittedAt: null,
    completedAt: null,
  },
  {
    id: 'm3',
    title: 'Prototype AI-Powered Internal Knowledge Search',
    description: 'Explore using RAG (Retrieval-Augmented Generation) to build a search tool over our internal wiki, Confluence, and Slack archives. This is an exploratory mission to evaluate feasibility and produce a working prototype.',
    successCriteria: [
      'Working prototype that can answer questions from internal docs',
      'Evaluation report comparing 3 embedding models',
      'Cost analysis for production deployment',
      'Demo presentation to engineering leadership',
    ],
    category: 'exploratory',
    rewardModel: 'fixed',
    estimatedHours: 60,
    deadline: '2026-05-01',
    requiredSkills: ['Machine Learning', 'Python', 'Cloud Architecture'],
    complexity: 2.8,
    urgency: 1.0,
    strategicImportance: 1.4,
    baseReward: 2352,
    dynamicReward: 2352,
    status: 'open',
    creatorId: 'u1',
    solverId: null,
    validatorId: null,
    applicants: [
      { userId: 'u2', proposal: 'I have experience with LangChain and vector databases. Can deliver a prototype in 4 weeks with a thorough evaluation.', appliedAt: '2026-03-25' },
    ],
    activityLog: [
      { id: 'a6', type: 'created', userId: 'u1', message: 'Mission posted to marketplace', timestamp: '2026-03-22T10:00:00Z' },
      { id: 'a7', type: 'applied', userId: 'u2', message: 'Marcus Chen submitted application', timestamp: '2026-03-25T16:00:00Z' },
    ],
    createdAt: '2026-03-22',
    submittedAt: null,
    completedAt: null,
  },
  {
    id: 'm4',
    title: 'Redesign Employee Onboarding Checklist',
    description: 'Current onboarding process is a 47-page PDF. Create an interactive, role-specific onboarding flow that guides new hires through their first 90 days with automated task tracking and manager notifications.',
    successCriteria: [
      'Interactive web-based checklist replaces PDF',
      'Role-specific paths for Engineering, Product, Design, and Sales',
      'Manager dashboard showing new hire progress',
      'Slack integration for automated reminders',
    ],
    category: 'operational',
    rewardModel: 'fixed',
    estimatedHours: 40,
    deadline: '2026-04-15',
    requiredSkills: ['React', 'Product Strategy', 'User Research'],
    complexity: 1.8,
    urgency: 1.2,
    strategicImportance: 1.0,
    baseReward: 864,
    dynamicReward: 890,
    status: 'under_review',
    creatorId: 'u4',
    solverId: 'u5',
    validatorId: 'u3',
    applicants: [
      { userId: 'u5', proposal: 'As a recent hire, I have fresh perspective on the onboarding pain points. I can build this in React with a clean UX.', appliedAt: '2026-03-02' },
    ],
    activityLog: [
      { id: 'a8', type: 'created', userId: 'u4', message: 'Mission posted to marketplace', timestamp: '2026-02-25T09:00:00Z' },
      { id: 'a9', type: 'applied', userId: 'u5', message: 'Leila Okonkwo submitted application', timestamp: '2026-03-02T11:00:00Z' },
      { id: 'a10', type: 'assigned', userId: 'u4', message: 'Leila Okonkwo selected as solver', timestamp: '2026-03-03T14:00:00Z' },
      { id: 'a11', type: 'submitted', userId: 'u5', message: 'Work submitted for validation', timestamp: '2026-03-25T17:00:00Z' },
    ],
    createdAt: '2026-02-25',
    submittedAt: '2026-03-25',
    completedAt: null,
  },
  {
    id: 'm5',
    title: 'Q2 Strategic Planning Data Package',
    description: 'Compile and analyze data needed for Q2 strategic planning: market trends, competitive analysis, internal performance metrics, and customer feedback synthesis. Deliver as an executive-ready slide deck with supporting data appendix.',
    successCriteria: [
      'Executive slide deck (max 20 slides) with key insights',
      'Data appendix with methodology documentation',
      'Competitive landscape map covering 5 main competitors',
      'Customer feedback synthesis from NPS and support tickets',
    ],
    category: 'strategic',
    rewardModel: 'fixed',
    estimatedHours: 50,
    deadline: '2026-04-05',
    requiredSkills: ['Data Analysis', 'Product Strategy', 'Data Visualization'],
    complexity: 2.2,
    urgency: 1.8,
    strategicImportance: 1.5,
    baseReward: 2376,
    dynamicReward: 2500,
    status: 'completed',
    creatorId: 'u1',
    solverId: 'u2',
    validatorId: 'u3',
    applicants: [
      { userId: 'u2', proposal: 'I can combine SQL analysis with market research. Have experience building exec decks.', appliedAt: '2026-02-12' },
    ],
    activityLog: [
      { id: 'a12', type: 'created', userId: 'u1', message: 'Mission posted to marketplace', timestamp: '2026-02-10T09:00:00Z' },
      { id: 'a13', type: 'applied', userId: 'u2', message: 'Marcus Chen submitted application', timestamp: '2026-02-12T13:00:00Z' },
      { id: 'a14', type: 'assigned', userId: 'u1', message: 'Marcus Chen selected as solver', timestamp: '2026-02-13T10:00:00Z' },
      { id: 'a15', type: 'submitted', userId: 'u2', message: 'Work submitted for validation', timestamp: '2026-03-10T16:00:00Z' },
      { id: 'a16', type: 'approved', userId: 'u3', message: 'Work approved — exceptional quality, thorough analysis', timestamp: '2026-03-12T11:00:00Z' },
      { id: 'a17', type: 'completed', userId: 'u1', message: 'Mission completed. 2,500 points distributed.', timestamp: '2026-03-12T11:30:00Z' },
    ],
    createdAt: '2026-02-10',
    submittedAt: '2026-03-10',
    completedAt: '2026-03-12',
  },
  {
    id: 'm6',
    title: 'Internal API Rate Limiting and Monitoring',
    description: 'Implement rate limiting across our internal API gateway and build a monitoring dashboard to track usage patterns, identify abuse, and alert on anomalies. Critical for platform stability as internal API traffic has grown 300% this quarter.',
    successCriteria: [
      'Rate limiting active on all internal API endpoints',
      'Per-team and per-service usage quotas configurable',
      'Monitoring dashboard with real-time traffic visualization',
      'Automated alerts for quota violations and anomalies',
    ],
    category: 'strategic',
    rewardModel: 'auction',
    estimatedHours: 90,
    deadline: '2026-05-20',
    requiredSkills: ['Cloud Architecture', 'DevOps', 'Go', 'System Design'],
    complexity: 2.6,
    urgency: 1.5,
    strategicImportance: 1.3,
    baseReward: 3834,
    dynamicReward: 3900,
    status: 'open',
    creatorId: 'u3',
    solverId: null,
    validatorId: null,
    applicants: [],
    activityLog: [
      { id: 'a18', type: 'created', userId: 'u3', message: 'Mission posted to marketplace', timestamp: '2026-03-26T09:00:00Z' },
    ],
    createdAt: '2026-03-26',
    submittedAt: null,
    completedAt: null,
  },
];

export const SEED_TRANSACTIONS: PointTransaction[] = [
  { id: 't1', userId: 'u2', amount: 2500, type: 'earned', missionId: 'm5', description: 'Completed: Q2 Strategic Planning Data Package', timestamp: '2026-03-12T11:30:00Z' },
  { id: 't2', userId: 'u2', amount: 250, type: 'bonus', missionId: 'm5', description: 'Quality bonus (+10%) for Q2 Strategic Planning', timestamp: '2026-03-12T11:30:00Z' },
  { id: 't3', userId: 'u3', amount: 250, type: 'earned', missionId: 'm5', description: 'Validation reward for Q2 Strategic Planning', timestamp: '2026-03-12T11:30:00Z' },
  { id: 't4', userId: 'u1', amount: 125, type: 'earned', missionId: 'm5', description: 'Creator reward for Q2 Strategic Planning', timestamp: '2026-03-12T11:30:00Z' },
  { id: 't5', userId: 'u2', amount: 1200, type: 'earned', missionId: 'm1', description: 'Milestone payment: Product Metrics Dashboard (phase 1)', timestamp: '2026-03-20T14:00:00Z' },
  { id: 't6', userId: 'u5', amount: 450, type: 'earned', missionId: 'm4', description: 'Partial: Onboarding Checklist (pending validation)', timestamp: '2026-03-25T17:00:00Z' },
];

export const ALL_SKILLS = [
  'TypeScript', 'React', 'Python', 'SQL', 'Go', 'Cloud Architecture',
  'Machine Learning', 'Data Analysis', 'Data Visualization', 'DevOps',
  'System Design', 'Security', 'Product Strategy', 'OKR Design',
  'User Research', 'Stakeholder Management', 'Program Management',
  'Innovation Frameworks', 'Statistics', 'Code Review',
];
